### ISSUE TITLE
How many FPS should we use?

### ISSUE THREAD

**Issue by debone** [mayaman26/p5jsCommunitySketches#21]
Hello community!
I'm starting my sketch and found that some are using 60fps and others the default... But shouldn't we be consistent on that?

Thanks!

**Comment by JobLeonard** [comment]
What's the FPS of the video? Wouldn't it make most sense to sync with that?

**Comment by mayaman** [comment]
Hi all,

The default frame rate in p5 is 60 frames per second, so whether someone specifies that or simply uses the default, it should be consistent. That's a good suggestion, but I don't think the sketches will need to sync fps with the video because they'll be running independently of the video clip (simply placed in the background with video clips over top).  Great question, thanks!
